### ISSUE TITLE
Steps for deep learning on AWS

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [alphagov/govuk-taxonomy-supervised-learning#38]
Some thoughts about running deep learning with tensorflow/keras on AWS

__Workflow__: 
* Instantiate databox with conda ami (`./databox.sh -a ami-1812bb61 -r eu-west-1 -i p2.xlarge up`)
* DataBoxVolume will fail to attach as some development tasks fail on this ami (see [issue](https://github.com/ukgovdatascience/databox/issues/24)). Log into the AWS console and delete this volume (or leave it to be deleted when you run `./databox -r eu-west-1 down`).
* Load the govuk-taxonomy-supervised-learning snapshot into a volume (through AWS console) and attach to the DataBox.
* Mount the data volume at `/data`
* SSH tunnel into the instance with `ssh -L localhost:8888:localhost:8888 ubuntu@<databox IP>`
* Make a copy of the coda env `tensorflow_p36` before making any changes, with `conda create --name <new env name> --clone tensorflow_p36` **NOTE:** This takes a really long time!.
* Set env vars (`DATADIR`) in new environment (consider installing direnv to make life simpler!)
* Install requirements into new environment. __Do this manually__. Don't do `pip install -r requirements.txt`, which will break the installation. Run the notebook: see what is missing, and then install that using pip install. Then create a new requirements file that is up to date __NOTE:__ It should only need sklearn!
* Run `jupyter notebook` on instance
* Log in to notebook server on your local machine by copying and pasting link generated on the server.
* To run tensorboard ensure that the tensorboard callback has been enabled in the model, then log into the instance again in a new terminal creating a new tunnel with `ssh -L localhost:6006:localhost:6006 ubuntu@<databox IP>`. Activate the correct environment that you created earlier with `conda create...` then run `tensorboard --log_dir=<path to logging>`.
* Ensure that your model is running on the instance GPU by running `nvidia-smi` in a new terminal on the instance (you can run this repeatedly with `watch -n 10 nvidia-smi` to update every 10 seconds).

__Thoughts going forward__:
* Move all generic pipeline tasks out of the deep learning notebooks, and into the data prep pipeline. The only thing that the deep learning instances should be doing is deep learning, no other data preparation. Preprocessed data can instead just be saved on S3 or on a volume snapshot.
* Split apart the data prep pipeline and the deep learning notebooks into a separate repo. These are likely to have different requirements, and we will not need to run deep learning on gov.uk infrastructure.

__Questions__:

* Where should the data be stored?
    * An S3 Bucket?
    * A volume/snapshot
    * Both? (present situation)
* Should the pipeline be executed on a remote instance, or run locally then uploaded?
* Do we need to output so many data cuts from the pipeline? And is compressed .csv.gz the right format (we could also use jsons or pickles) - do we lose any information by flattening to csv, and then reimporting (e.g. dtype) and would it be better to keep it in a more informative format? 

__Notes on a first run__: 

* Training an epoch is very fast (<2 minute) for [this notebook](https://github.com/ukgovdatascience/govuk-taxonomy-supervised-learning/blob/master/python/notebooks/ML_notebooks/CNN/CNN-labelled_level2_learn_embeddings.ipynb) - there is a version fixed for AWS added in #39.
* The end of epoch evaluation is incredibly slow, at least ten minutes after each epoch. This is run on the instance CPU (and so may be faster on a bigger instance), but we may also reduce the frequency of this task?

__Discuss: GO__

**Comment by ellieking17** [comment]
Think these instructions should be added to README in CNN directory

**Comment by ivyleavedtoadflax** [comment]
See #44.
